-- 0001_init.sql — baseline migration.
--
-- Purpose: initialize the migration chain and prove the full runner path
-- (embed -> checksum -> advisory lock -> transactional apply -> record) in
-- every environment, including CI. schema_migrations itself is created by the
-- runner before the first migration executes; this file establishes version 1
-- as the known-good starting point.
--
-- The first real schema (identity/RBAC/audit/jobs) arrives in 0002+ with
-- Phase 1. Do not edit this file after release — add new migrations instead.

SELECT 1;
