package identity

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/bukansembarangkong/jawaker-panel/internal/audit"
	"github.com/jackc/pgx/v5"
)

// TOTP enrollment lifecycle (SECURITY.md §3: TOTP 2FA).
//
// The shared secret itself never lives in this table: totp_credentials stores
// only a `secret://` reference into the secret subsystem, so a database dump
// does not yield working second factors.

// TOTPCredential is one enrollment row.
type TOTPCredential struct {
	ID string
	// SecretRef points into the secret subsystem.
	SecretRef string
	// ConfirmedAt is nil until the user proves possession of the secret by
	// submitting a valid code. An unconfirmed enrollment is never usable.
	ConfirmedAt *time.Time
	// LastUsedStep is the most recently consumed time step (anti-replay).
	LastUsedStep *int64
	CreatedAt    time.Time
	DisabledAt   *time.Time
}

// CreateTOTPEnrollment creates an UNCONFIRMED enrollment and returns its id and
// the secret reference the caller must seal the shared secret under.
//
// Confirmation is a separate step on purpose: an enrollment that is usable
// immediately would lock a user out of their own account the moment the
// provisioning step fails, e.g. a mistyped scan.
//
// It ONLY supersedes a previous PENDING enrollment, never the active one. That
// distinction is a security property, not tidiness: demoting the confirmed
// factor here would leave the account with no second factor between enrolling
// and confirming, so a request that enrolled and then simply stopped — no code
// required — would disarm MFA. The active factor is demoted only in
// ConfirmTOTPEnrollment, where the replacement has just been proven usable.
//
// The secret reference is generated by the database so each enrollment has its
// own: a shared per-user reference would overwrite the live secret of the
// enrollment still in force.
func CreateTOTPEnrollment(ctx context.Context, db Querier, userID, requestID string) (id, secretRef string, err error) {
	tx, err := db.Begin(ctx)
	if err != nil {
		return "", "", fmt.Errorf("identity: begin TOTP enrollment: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Supersede a previous candidate. Its secret is unreachable afterwards, so
	// no further cleanup is needed. The old row is retained because a disabled
	// enrollment is part of the account's security history.
	if _, err := tx.Exec(ctx, `
		UPDATE totp_credentials SET disabled_at = now()
		WHERE user_id = $1 AND confirmed_at IS NULL AND disabled_at IS NULL`, userID); err != nil {
		return "", "", fmt.Errorf("identity: supersede pending enrollment: %w", err)
	}

	if err := tx.QueryRow(ctx, `
		INSERT INTO totp_credentials (user_id, secret_ref)
		VALUES ($1, 'secret://totp/' || gen_random_uuid())
		RETURNING id, secret_ref`, userID).Scan(&id, &secretRef); err != nil {
		return "", "", fmt.Errorf("identity: create TOTP enrollment: %w", err)
	}

	if err := audit.Record(ctx, tx, audit.Event{
		ActorType:    audit.ActorUser,
		ActorID:      userID,
		Action:       "mfa.totp.enroll",
		ResourceType: "totp_credential",
		ResourceID:   id,
		RequestID:    requestID,
		Result:       audit.ResultSuccess,
	}); err != nil {
		return "", "", err
	}
	if err := tx.Commit(ctx); err != nil {
		return "", "", fmt.Errorf("identity: commit TOTP enrollment: %w", err)
	}
	return id, secretRef, nil
}

// GetTOTPEnrollment loads one enrollment by id.
func GetTOTPEnrollment(ctx context.Context, db Queryer, id string) (TOTPCredential, error) {
	return scanTOTP(db.QueryRow(ctx, `
		SELECT id, secret_ref, confirmed_at, last_used_step, created_at, disabled_at
		FROM totp_credentials WHERE id = $1`, id))
}

// GetPendingTOTP loads the unconfirmed, enabled enrollment for a user.
//
// The confirmation flow reads the candidate through this rather than an id the
// client supplies, so a caller cannot ask the server to confirm someone else's
// enrollment: the row is selected by the SESSION's user id.
func GetPendingTOTP(ctx context.Context, db Queryer, userID string) (TOTPCredential, error) {
	return scanTOTP(db.QueryRow(ctx, `
		SELECT id, secret_ref, confirmed_at, last_used_step, created_at, disabled_at
		FROM totp_credentials
		WHERE user_id = $1 AND confirmed_at IS NULL AND disabled_at IS NULL
		ORDER BY created_at DESC LIMIT 1`, userID))
}

// GetActiveTOTP loads the confirmed, enabled enrollment for a user.
//
// A user with an UNCONFIRMED enrollment has ErrNotFound here, which is what
// keeps a half-finished enrollment from requiring a second factor nobody can
// produce.
func GetActiveTOTP(ctx context.Context, db Queryer, userID string) (TOTPCredential, error) {
	return scanTOTP(db.QueryRow(ctx, `
		SELECT id, secret_ref, confirmed_at, last_used_step, created_at, disabled_at
		FROM totp_credentials
		WHERE user_id = $1 AND confirmed_at IS NOT NULL AND disabled_at IS NULL
		ORDER BY confirmed_at DESC LIMIT 1`, userID))
}

func scanTOTP(row pgx.Row) (TOTPCredential, error) {
	var c TOTPCredential
	err := row.Scan(&c.ID, &c.SecretRef, &c.ConfirmedAt, &c.LastUsedStep,
		&c.CreatedAt, &c.DisabledAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return TOTPCredential{}, ErrNotFound
	}
	if err != nil {
		return TOTPCredential{}, fmt.Errorf("identity: load TOTP enrollment: %w", err)
	}
	return c, nil
}

// ConfirmTOTPEnrollment promotes a pending enrollment to the factor in force,
// demoting whatever was active before it, and records the code's time step.
//
// All three happen in ONE transaction because they are one state change. The
// caller has already proven possession of the new secret; the only ordering
// that is safe is "the replacement becomes active as the old one stops being
// active". A gap in either direction is exploitable: demote-then-confirm lets a
// failure leave the account with no factor, confirm-then-demote leaves two.
//
// The step is recorded here rather than through ConsumeTOTPStep because that
// function only accepts a CONFIRMED enrollment, and this one is confirmed by
// this very statement. The anti-replay guard is therefore expressed in the
// WHERE clause: `last_used_step < $3` means a replayed code cannot confirm (and
// cannot re-confirm) an enrollment, and two simultaneous confirmations race in
// the DATABASE, where exactly one gets rowsAffected == 1.
func ConfirmTOTPEnrollment(ctx context.Context, db Querier, enrollmentID, actorID string, step int64, requestID string) error {
	tx, err := db.Begin(ctx)
	if err != nil {
		return fmt.Errorf("identity: begin TOTP confirmation: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Demote the factor currently in force. It keeps its history row; only the
	// "usable" flag is cleared.
	if _, demoteErr := tx.Exec(ctx, `
		UPDATE totp_credentials SET disabled_at = now()
		WHERE id <> $1 AND confirmed_at IS NOT NULL AND disabled_at IS NULL`,
		enrollmentID); demoteErr != nil {
		return fmt.Errorf("identity: demote previous TOTP enrollment: %w", demoteErr)
	}

	tag, err := tx.Exec(ctx, `
		UPDATE totp_credentials
		SET confirmed_at = now(), last_used_step = $2
		WHERE id = $1 AND confirmed_at IS NULL AND disabled_at IS NULL
		  AND (last_used_step IS NULL OR last_used_step < $2)`, enrollmentID, step)
	if err != nil {
		return fmt.Errorf("identity: confirm TOTP enrollment: %w", err)
	}
	if tag.RowsAffected() == 0 {
		// Already confirmed, disabled, superseded, or the code was replayed.
		// Reported as not-found rather than silently succeeding, so a double
		// confirmation is visible; the tx rollback undoes the demotion above.
		return ErrNotFound
	}
	if err := audit.Record(ctx, tx, audit.Event{
		ActorType:    audit.ActorUser,
		ActorID:      actorID,
		Action:       "mfa.totp.confirm",
		ResourceType: "totp_credential",
		ResourceID:   enrollmentID,
		RequestID:    requestID,
		Result:       audit.ResultSuccess,
	}); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("identity: commit TOTP confirmation: %w", err)
	}
	return nil
}

// ConsumeTOTPStep records a time step as used, returning false when it was
// already consumed.
//
// This is the anti-replay guarantee. It runs as a single conditional UPDATE, so
// two requests presenting the same code race in the DATABASE: exactly one gets
// rowsAffected == 1. A read-then-write in application code would let both in,
// because both reads would complete before either write — the classic
// check-then-act race, and precisely the case an attacker replaying an observed
// code would exploit.
//
// The step must be monotonic: an older step is refused even if unused, so a code
// captured earlier cannot be replayed later in the window.
func ConsumeTOTPStep(ctx context.Context, db Execer, enrollmentID string, step int64) (bool, error) {
	tag, err := db.Exec(ctx, `
		UPDATE totp_credentials
		SET last_used_step = $2
		WHERE id = $1
		  AND confirmed_at IS NOT NULL
		  AND disabled_at IS NULL
		  AND (last_used_step IS NULL OR last_used_step < $2)`, enrollmentID, step)
	if err != nil {
		return false, fmt.Errorf("identity: consume TOTP step: %w", err)
	}
	return tag.RowsAffected() == 1, nil
}

// DisableTOTP disables every enabled enrollment for a user and audits it. Used
// when a user loses their authenticator: the rows are retained with disabled_at
// so the history of enrollments stays visible.
//
// Recovery codes are deleted in the SAME transaction. They exist to bypass the
// second factor, so leaving them valid after the factor is gone would let anyone
// holding one satisfy a check that no longer applies — a credential outliving the
// policy it belonged to.
//
// Disabling a second factor is the single highest-impact identity change an
// account owner can make, so it is audited transactionally with the reason
// recorded: an account whose MFA vanished without explanation is exactly the
// signal an incident reviewer needs.
//
// Returns the number of recovery codes revoked, for the caller to report.
func DisableTOTP(ctx context.Context, db Querier, userID, actorID, reason, requestID string) (int64, error) {
	if strings.TrimSpace(reason) == "" {
		return 0, errors.New("identity: a reason is required to disable a second factor")
	}
	tx, err := db.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("identity: begin TOTP disable: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	tag, err := tx.Exec(ctx, `
		UPDATE totp_credentials SET disabled_at = now()
		WHERE user_id = $1 AND disabled_at IS NULL`, userID)
	if err != nil {
		return 0, fmt.Errorf("identity: disable TOTP: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return 0, ErrNotFound
	}

	codes, err := RevokeRecoveryCodes(ctx, tx, userID)
	if err != nil {
		return 0, err
	}

	if err := audit.Record(ctx, tx, audit.Event{
		ActorType:    audit.ActorUser,
		ActorID:      actorID,
		Action:       "mfa.totp.disable",
		ResourceType: "user",
		ResourceID:   userID,
		RequestID:    requestID,
		Result:       audit.ResultSuccess,
		Reason:       reason,
		Context:      map[string]any{"recovery_codes_revoked": codes},
	}); err != nil {
		return 0, err
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("identity: commit TOTP disable: %w", err)
	}
	return codes, nil
}

// TOTPStatus summarizes a user's second-factor state for the UI.
type TOTPStatus struct {
	// Enrolled reports a confirmed, enabled enrollment.
	Enrolled bool
	// Pending reports an unconfirmed enrollment awaiting confirmation.
	Pending bool
}

// GetTOTPStatus reports the second-factor state without exposing the secret.
func GetTOTPStatus(ctx context.Context, db Queryer, userID string) (TOTPStatus, error) {
	var status TOTPStatus
	err := db.QueryRow(ctx, `
		SELECT
		  EXISTS (SELECT 1 FROM totp_credentials
		           WHERE user_id = $1 AND confirmed_at IS NOT NULL AND disabled_at IS NULL),
		  EXISTS (SELECT 1 FROM totp_credentials
		           WHERE user_id = $1 AND confirmed_at IS NULL AND disabled_at IS NULL)`,
		userID).Scan(&status.Enrolled, &status.Pending)
	if err != nil {
		return TOTPStatus{}, fmt.Errorf("identity: TOTP status: %w", err)
	}
	return status, nil
}
